package com.partseazy.android.utility;

/**
 * Created by gaurav on 07/12/16.
 */

public enum HolderType {

    VIEW_IMAGE_BANNER,
    VIEW_REGISTER_MOBILE,
    VIEW_CART_MESSAGE,
    VIEW_CART_INFO,
    VIEW_CART_PROMOCODE,
    VIEW_CART_SHIPPING,
    VIEW_CART_ORDER_DETAIL,
    VIEW_CART_CFORM,
    VIEW_PAY_PROGRESSBAR,
    VIEW_ADDRESS_PAGER,
    VIEW_PAY_ADDRESS,
    VIEW_PAY_PRODUCT_DETAIL,
    VIEW_PAY_PROMOTION_CODE,
    VIEW_PAY_SHIPPING_TYPE,
    VIEW_PAY_ORDER_DETAIL,
    VIEW_PAY_OPTION,
    VIEW_PAY_CALL,
    VIEW_PRODUCT_BANNER,
    VIEW_PRODUCT_INFO,
    VIEW_PRODUCT_REFURBISHED,
    VIEW_PRODUCT_DETAILS,
    VIEW_PRODUCT_SUPPLIER,
    VIEW_PRODUCT_RETURN_POLICY,
    VIEW_PRODUCT_SAMPLE,
    VIEW_PRODUCT_DIAL,

    VIEW_HOME_LARGE_BANNER,
    VIEW_HOME_CATEGORY_GRID,
    VIEW_HOME_SHOP_BY_BRAND,
    VIEW_HOME_PRODUCT_CARD,
    VIEW_HOME_CARD_BANNER,
    VIEW_HOME_SEARCH_BY_PRODUCT,
    VIEW_PRODUCT_SIMILAR,
    VIEW_HOME_CLICK_TO_ORDER,
    VIEW_HOME_CALL_TO_ORDER,
    VIEW_HOME_RECENT_ORDER,

    VIEW_ORDER_SUMMARY_ORDER_CARD,
    VIEW_ORDER_SUMMARY_SHIPPING_CARD,
    VIEW_ORDER_SUMMARY_BILLING_CARD,
    VIEW_ORDER_PAYMENT_SUMMARY_CARD,
    VIEW_ORDER_PRODUCT_SUMMARY_CARD,

    VIEW_NAV_DRAWER_HEADER,
    VIEW_NAV_DRAWER_CATEGORY_ITEM,
    VIEW_NAV_DRAWER_ICON_ITEM,
    VIEW_NAV_DRAWER_INFO_ITEM,
    VIEW_NAV_DRAWER_HOME_ITEM,

    VIEW_DEAL_BANNER,
    VIEW_DEAL_INFO,
    VIEW_DEAL_SKU,
    VIEW_DEAL_YOUTUBE,
    VIEW_DEAL_YOUTUBE_CARD,
    VIEW_DEAL_DESCRIPTION,
    VIEW_DEAL_ORDER_HISTORY,
    VIEW_DEAL_DEMO_LIST,
    VIEW_DEAL_SUPPLIER,
    VIEW_DEAL_TERMS_CONDITION,

    VIEW_ORDER_PRODUCT_INFO,
    VIEW_ORDER_PAYMENT_SUMMARY,
    VIEW_BOOKING_PAYMENT_STATUS,
    VIEW_ORDER_SHIPPING,
    VIEW_ORDER_STATUS,

    VIEW_DEAL_BUY_INFO,
    VIEW_DEAL_NO_DEAL,
    VIEW_DEAL_BUY_CARD,

    VIEW_DEAL_FILTER_SWITCH_CARD,
    VIEW_DEAL_FILTER_CATEGORY_CARD,

    VIEW_DEAL_NEW_PIC,
    VIEW_DEAL_NEW_PIC_ICON,

    VIEW_BOOKING_PROGRESS,
    VIEW_BOOKING_ADDRESS,
    VIEW_BOOKING_SUMMARY,
    VIEW_BOKKING_SHIPPING,

    VIEW_BILLING_ADDRESS,


    VIEW_DEAL_PROMOTE_PROGRESS,
    VIEW_DEAL_PROMOTE_CITY,
    VIEW_DEAL_PROMOTE_AREA,
    VIEW_DEAL_RETAILER_PREVIEW,


    VIEW_SHOP_BANNER,
    VIEW_SHOP_INFO_CARD,
    VIEW_SHOP_DETAILS_CARD,
    VIEW_SHOP_CATEGORY_BRAND_CARD,
    VIEW_SHOP_OWNER_CARD,
    VIEW_SHOP_DETAIL_CARD,
    VIEW_SHOP_CONTACT_CARD,
    VIEW_SHOP_INFO,

    VIEW_RETAILER_BASIC_INFO,
    VIEW_RETAILER_KYC_INFO,
    VIEW_RETAILER_BUSINESS_PROFILE,
    VIEW_RETAILER_FINANCIAL_PROFILE

}
